name = "RAGTools"
uuid = "16ddad29-bbe8-45a7-857d-3d9514eb0023"
authors = ["J S <49557684+svilupp@users.noreply.github.com> and contributors"]
version = "0.7.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PromptingTools = "670122d1-24a8-4d70-bfce-740807c42192"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Snowball = "fb8f903a-0164-4e73-9ffe-431110250c3b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[weakdeps]
FlashRank = "22cc3f58-1757-4700-bb45-2032706e5a8d"

[extensions]
FlashRankPromptingToolsExt = ["FlashRank"]

[compat]
AbstractTrees = "0.4.5"
Aqua = "0.8"
FlashRank = "0.4.1"
HTTP = "1.10.15"
JSON3 = "1.14.1"
LinearAlgebra = "1"
ProgressMeter = "1.10"
PromptingTools = "0.75 - 0.82"
Random = "1"
Snowball = "0.1"
SparseArrays = "1"
Test = "1"
Unicode = "1"
julia = "1.10, 1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
